image: python:2.7
env:
  - PYTHONPATH="."
script:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .
  - mamba
notify:
  hipchat:
    room: $$hipchatRoom
    token: $$hipchatToken
    on_started: true
    on_success: true
    on_failure: true
